/**
 * Turning an approved login into this computer's credentials.
 *
 * A login request publishes a one-time public key; whoever approves it seals the
 * account key against that key and the relay hands the sealed bytes back. Two
 * flows reach this point — the interactive terminal login and the login the
 * desktop shell asks for — and both must read the sealed bytes the same way, so
 * the reading lives here rather than in either caller.
 *
 * Nothing here trusts the bytes: a bundle that does not decrypt, or decrypts to
 * something that is not an account key, yields no credentials at all.
 */

import tweetnacl from 'tweetnacl';

import type { Credentials } from '@/persistence';

const LEGACY_SECRET_LENGTH = 32;
const DATA_KEY_TAG = 0;
const DATA_KEY_BUNDLE_LENGTH = 33;

export function decryptWithEphemeralKey(
  encryptedBundle: Uint8Array,
  recipientSecretKey: Uint8Array,
): Uint8Array | null {
  if (encryptedBundle.length <= 32 + tweetnacl.box.nonceLength) {
    return null;
  }
  const ephemeralPublicKey = encryptedBundle.slice(0, 32);
  const nonce = encryptedBundle.slice(32, 32 + tweetnacl.box.nonceLength);
  const encrypted = encryptedBundle.slice(32 + tweetnacl.box.nonceLength);

  return tweetnacl.box.open(encrypted, nonce, ephemeralPublicKey, recipientSecretKey);
}

/**
 * The credentials an approved login yields, or null when the response is not one.
 * `machineKey` is this computer's own key: it is generated by the caller and only
 * kept when the account key arrives in the form that needs it.
 */
export function credentialsFromSealedResponse(args: {
  sealed: Uint8Array;
  token: string;
  ephemeralSecretKey: Uint8Array;
  machineKey: Uint8Array;
}): Credentials | null {
  const decrypted = decryptWithEphemeralKey(args.sealed, args.ephemeralSecretKey);
  if (!decrypted) {
    return null;
  }
  if (decrypted.length === LEGACY_SECRET_LENGTH) {
    return {
      token: args.token,
      encryption: { type: 'legacy', secret: decrypted },
    };
  }
  if (decrypted.length >= DATA_KEY_BUNDLE_LENGTH && decrypted[0] === DATA_KEY_TAG) {
    return {
      token: args.token,
      encryption: {
        type: 'dataKey',
        publicKey: decrypted.slice(1, DATA_KEY_BUNDLE_LENGTH),
        machineKey: args.machineKey,
      },
    };
  }
  return null;
}
